### ISSUE TITLE
No default icons from pack shown; (fixed) Crash on Search

### ISSUE THREAD

**Issue by ltGuillaume** [TBog/TBLauncher#134]
# Description #

```
I/ActivityTaskManager(1109):  START u0 {act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10000100 cmp=rocks.tbog.tblauncher/.TBLauncherActivity (has extras)} from uid 0
W/ActivityThread(5318):  handleWindowVisibility: no activity for token android.os.BinderProxy@a8f98a8
W/auditd  (372):  type=1325 audit(0.0:12447): table=filter family=2 entries=423
W/auditd  (372):  type=1320 audit(0.0:12447): 
W/auditd  (372):  type=1325 audit(0.0:12448): table=filter family=10 entries=245
W/auditd  (372):  type=1320 audit(0.0:12448): 
E/system_server(1109):  Invalid ID 0x00000000.
I/netd    (1001):  firewallSetUidRule(2, 10080, 2) <12.24ms>
I/netd    (1001):  firewallSetUidRule(2, 10041, 2) <6.89ms>
D/TBog    (5318):  Ctx: rocks.tbog.tblauncher.TBLauncherActivity@cae76a7 | Res: android.content.res.Resources@a999754
D/TBog    (5318):  Ctx: androidx.appcompat.view.ContextThemeWrapper@e7936fd | Res: android.content.res.Resources@a999754
D/TBog    (5318):  Ctx: android.app.ContextImpl@d0baff2 | Res: android.content.res.Resources@4c1d643
D/ImageWallpaper(1460):  wallpaper visibility changes to: true
W/auditd  (372):  type=1325 audit(0.0:12449): table=filter family=2 entries=424
W/auditd  (372):  type=1320 audit(0.0:12449): 
W/auditd  (372):  type=1325 audit(0.0:12450): table=filter family=10 entries=246
W/auditd  (372):  type=1320 audit(0.0:12450): 
D/Behaviour(5318):  desktop changed WIDGET -> SEARCH
D/RemoteViewsService(12192):  onCreate
I/Behaviour(5318):  Keyboard - SHOW
D/RemoteViewsFactory(12192):  50 instance:3 getViewTypeCount:14
D/AndroidRuntime(5318):  Shutting down VM
D/RemoteViewsFactory(12192):  50 instance:3 getCount:45 0
E/AndroidRuntime(5318):  FATAL EXCEPTION: main
E/AndroidRuntime(5318):  Process: rocks.tbog.tblauncher, PID: 5318
E/AndroidRuntime(5318):  java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
E/AndroidRuntime(5318):  	at rocks.tbog.tblauncher.quicklist.QuickList.populateList(QuickList.java:132)
E/AndroidRuntime(5318):  	at rocks.tbog.tblauncher.quicklist.QuickList.show(QuickList.java:353)
E/AndroidRuntime(5318):  	at rocks.tbog.tblauncher.quicklist.QuickList.showQuickList(QuickList.java:347)
E/AndroidRuntime(5318):  	at rocks.tbog.tblauncher.Behaviour.showDesktop(Behaviour.java:474)
E/AndroidRuntime(5318):  	at rocks.tbog.tblauncher.Behaviour.switchToDesktop(Behaviour.java:463)
E/AndroidRuntime(5318):  	at rocks.tbog.tblauncher.Behaviour.executeAction(Behaviour.java:1352)
E/AndroidRuntime(5318):  	at rocks.tbog.tblauncher.Behaviour.onPostCreate(Behaviour.java:353)
E/AndroidRuntime(5318):  	at rocks.tbog.tblauncher.TBLauncherActivity.onPostCreate(TBLauncherActivity.java:146)
E/AndroidRuntime(5318):  	at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1380)
E/AndroidRuntime(5318):  	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3321)
E/AndroidRuntime(5318):  	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
E/AndroidRuntime(5318):  	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
E/AndroidRuntime(5318):  	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
E/AndroidRuntime(5318):  	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
E/AndroidRuntime(5318):  	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
E/AndroidRuntime(5318):  	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(5318):  	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(5318):  	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime(5318):  	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(5318):  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
E/AndroidRuntime(5318):  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
I/DropBoxManagerService(1109):  add tag=data_app_crash isTagEnabled=true flags=0x2
I/ndroid.systemu(1460):  NativeAlloc concurrent copying GC freed 15831(797KB) AllocSpace objects, 2(40KB) LOS objects, 49% free, 7876KB/15MB, paused 387us total 147.641ms
W/ActivityTaskManager(1109):    Force finishing activity rocks.tbog.tblauncher/.TBLauncherActivity
I/ActivityTaskManager(1109):  Clearing package preferred activities from rocks.tbog.tblauncher
I/ActivityManager(1109):  Showing crash dialog for package rocks.tbog.tblauncher u0
E/system_server(1109):  Invalid ID 0x00000000.
I/RoleControllerServiceImpl(11335):  Adding package as fallback role holder, package: rocks.tbog.tblauncher, role: android.app.role.HOME
W/Adreno-EGL(1109):  <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
I/RoleUserState(1109):  Wrote roles.xml successfully
W/ActivityTaskManager(1109):  Activity top resumed state loss timeout for ActivityRecord{61c4a6f u0 rocks.tbog.tblauncher/.TBLauncherActivity t470 f}
W/ActivityTaskManager(1109):  Activity pause timeout for ActivityRecord{61c4a6f u0 rocks.tbog.tblauncher/.TBLauncherActivity t470 f}
W/Adreno-EGL(1109):  <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
W/Adreno-EGL(10718):  <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
D/ImageWallpaper(1460):  wallpaper visibility changes to: false
W/WindowManager(1109):  Failed looking up window callers=com.android.server.wm.WindowManagerService.windowForClientLocked:5318 com.android.server.wm.WindowManagerService.removeWindow:1782 com.android.server.wm.Session.remove:176 
W/ActivityTaskManager(1109):    Force finishing activity rocks.tbog.tblauncher/.TBLauncherActivity
D/OpenGLRenderer(1109):  endAllActiveAnimators on 0x75e2b400 (RippleDrawable) with handle 0x94dab770
E/InputDispatcher(1109):  Window handle Window{7ae8c40 u0 Application Error: rocks.tbog.tblauncher} has no registered input channel
I/ActivityManager(1109):  Killing 5318:rocks.tbog.tblauncher/u0a360 (adj 600): crash
W/ActivityManager(1109):  setHasOverlayUi called on unknown pid: 5318
I/Zygote  (998):  Process 5318 exited due to signal 9 (Killed)
I/libprocessgroup(1109):  Successfully killed process cgroup uid 10360 pid 5318 in 132ms
V/StatusBar(1460):  mStatusBarWindow: com.android.systemui.statusbar.phone.StatusBarWindowView{3eabdc V.E...... ........ 0,0-1080,65} canPanelBeCollapsed(): false
I/ActivityTaskManager(1109):  START u0 {act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10000100 cmp=rocks.tbog.tblauncher/.TBLauncherActivity (has extras)} from uid 0
```

## Context ##

I press the Home button in order to go to the Search desktop.

## Steps to Reproduce ##

To reproduce the behavior:
1. (I have) set Home button activity to show search desktop
2. Click on Home button from within another app
3. Once in a while, TBLauncher crashes

## Device info ##

  * OS: Android 10
  * TinyBit Launcher version: v6.2

**Comment by ltGuillaume** [comment]
In the 6.2 replace async build, the following happened 3 times now:

```
E/AndroidRuntime(10655):  FATAL EXCEPTION: main
E/AndroidRuntime(10655):  Process: rocks.tbog.tblauncher, PID: 10655
E/AndroidRuntime(10655):  java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
E/AndroidRuntime(10655):  	at rocks.tbog.tblauncher.quicklist.QuickList.populateList(QuickList.java:132)
E/AndroidRuntime(10655):  	at rocks.tbog.tblauncher.quicklist.QuickList.show(QuickList.java:353)
E/AndroidRuntime(10655):  	at rocks.tbog.tblauncher.quicklist.QuickList.showQuickList(QuickList.java:347)
E/AndroidRuntime(10655):  	at rocks.tbog.tblauncher.Behaviour.showDesktop(Behaviour.java:474)
E/AndroidRuntime(10655):  	at rocks.tbog.tblauncher.Behaviour.switchToDesktop(Behaviour.java:463)
E/AndroidRuntime(10655):  	at rocks.tbog.tblauncher.Behaviour.executeAction(Behaviour.java:1352)
E/AndroidRuntime(10655):  	at rocks.tbog.tblauncher.Behaviour.onPostCreate(Behaviour.java:353)
E/AndroidRuntime(10655):  	at rocks.tbog.tblauncher.TBLauncherActivity.onPostCreate(TBLauncherActivity.java:146)
E/AndroidRuntime(10655):  	at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1380)
E/AndroidRuntime(10655):  	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3321)
E/AndroidRuntime(10655):  	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
E/AndroidRuntime(10655):  	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
E/AndroidRuntime(10655):  	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
E/AndroidRuntime(10655):  	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
E/AndroidRuntime(10655):  	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
E/AndroidRuntime(10655):  	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(10655):  	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(10655):  	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime(10655):  	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10655):  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
E/AndroidRuntime(10655):  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```

**Comment by TBog** [comment]
> In the 6.2 replace async build, the following happened 3 times

It's strange, the callstack is wrong.
`at rocks.tbog.tblauncher.quicklist.QuickList.populateList(QuickList.java:132)` says that there is a vector access at line 132, but that line is a comment.
I'll rebuild and re-upload the apk when I get to the PC.

**Comment by ltGuillaume** [comment]
Following up on this, while TBLauncher doesn't crash anymore, in the situations that it previously would crash, it now stops showing icons that come directly from the icons pack I'm using (Whicons). So, for every _default_ icon that's in the Whicons pack, the following happens:

![image](https://user-images.githubusercontent.com/4777345/111347868-e96aef00-867f-11eb-9b86-87a5aaf32cef.png)

Icons that I set myself (also coming from Whicons) do show up.

If I close TBLauncher, all icons will show up again. If I then return to TBLauncher from another app after some time, the above happens again.

I have tried with all available icon caching options, but even the safest (`Cache Icons` on, the other two off) exhibits this behavior.

**Comment by ltGuillaume** [comment]
The above _may_ have something to do with https://github.com/TBog/TBLauncher/issues/127#issuecomment-802741834

**Comment by ltGuillaume** [comment]
I don't see a commit since https://github.com/TBog/TBLauncher/commit/da33796e81c894acd4f89caa181e922a2cd08419 that has addressed https://github.com/TBog/TBLauncher/issues/134#issuecomment-800436848, right?

**Comment by TBog** [comment]
Not yet. I'll have to examine the icon loading logic more closely.
Forgot about this. It's a closed issue after all...

**Comment by ltGuillaume** [comment]
Well you closed it only 2 hours ago 😉

**Comment by TBog** [comment]
it's automatically closed when a commit with a fix is merged to master

**Comment by TBog** [comment]
Please check if it's fixed in [v6.3-dev.1](https://github.com/TBog/TBLauncher/releases/tag/v6.3-dev.1)

**Comment by ltGuillaume** [comment]
Oof that loading icon is hella big and sooo annoying 🙈

**Comment by TBog** [comment]
> But oof that loading icon is hella big and sooo annoying. I feel all restless just by looking at it. 🙈

I'll add a toggle to disable the arrows. Leave empty space.

**Comment by ltGuillaume** [comment]
Errr I guess something like this https://gist.github.com/riccardoscalco/22300f7899483335a8df23b4dfc13b62 (but I would be very happy with the toggle to disable that animation).

**Comment by TBog** [comment]
> What's also strange is that the icons that previously wouldn't show (default icons from icon pack) won't have animated placeholder

This is not good. Something is not going according to the plan. I'll have to investigate further.

**Comment by TBog** [comment]
@ltGuillaume I can't reproduce the missing loading icons bug when using an icon pack.

**Comment by ltGuillaume** [comment]
I meant that the loading icon _would show_ but that it would not animate. For me personally it wouldn't matter if there's an option to remove the placeholder altogether, as you suggested. It was just funny to see some of the arrows spinning, and others not.

**Comment by ltGuillaume** [comment]
Sometimes it takes over 10 minutes before the icons of a pack are applied, sometimes they don't get applied at all. Would it perhaps be an option to add a feature to save all default pack icons that are in use as a custom icon, so that everything is loaded from TBLauncher's app data? This way, the icon pack doesn't have to be searched anymore on start-up, which would circumvent the current issues.

**Comment by TBog** [comment]
Can you check if it's fixed in build [v6.4-add_pages](https://github.com/TBog/TBLauncher/releases/tag/v6.4-add_pages)?

**Comment by ltGuillaume** [comment]
I installed it a couple of hours ago (still had to backup and restore data with Titanium because of "downgrade" 😉), so far it's looking very promising!!

**Comment by TBog** [comment]
> still had to backup and restore data with Titanium

is the included backup feature not working properly?

can Titanium restore shortcuts?

**Comment by ltGuillaume** [comment]
> > still had to backup and restore data with Titanium
> 
> is the included backup feature not working properly?
> 
> can Titanium restore shortcuts?

Yes, both widgets and shortcuts were preserved.

I have used the included backup feature before, but I think I had to recreate the widgets and shortcuts.

**Comment by TBog** [comment]
Is Titanium using root?
Can we close this issue?

**Comment by ltGuillaume** [comment]
Yeah it's using root.

Not yet, I'm still testing, since I didn't much have time today.

**Comment by ltGuillaume** [comment]
This seems to have been fixed! Thank you! 🙂
