### ISSUE TITLE
Crashes when not on foreground

### ISSUE THREAD

**Issue by ltGuillaume** [TBog/TBLauncher#154]
# Description #

TBLauncher crashes even when it's not on the foreground.

```
W/tbog.tblaunche(20672):  Long monitor contention with owner UtilAsync #2 (20714) at long android.content.res.AssetManager.nativeOpenXmlAsset(long, int, java.lang.String)(AssetManager.java:-2) waiters=0 in void rocks.tbog.tblauncher.icons.IconPackXML.load(android.content.pm.PackageManager) for 21.828s
I/IconsHandler(20672):  [end] loading default icon pack: com.whicons.iconpack
I/time    (20672):  21sec 851ms to load icon pack com.whicons.iconpack
D/AndroidRuntime(20672):  Shutting down VM
W/tbog.tblaunche(20672):  Long monitor contention with owner UtilAsync #2 (20714) at long android.content.res.AssetManager.nativeOpenXmlAsset(long, int, java.lang.String)(AssetManager.java:-2) waiters=1 in void rocks.tbog.tblauncher.icons.IconPackXML.load(android.content.pm.PackageManager) for 21.633s
W/tbog.tblaunche(20672):  Long monitor contention with owner UtilAsync #2 (20714) at long android.content.res.AssetManager.nativeOpenXmlAsset(long, int, java.lang.String)(AssetManager.java:-2) waiters=2 in void rocks.tbog.tblauncher.icons.IconPackXML.load(android.content.pm.PackageManager) for 21.585s
W/tbog.tblaunche(20672):  Long monitor contention with owner UtilAsync #2 (20714) at long android.content.res.AssetManager.nativeOpenXmlAsset(long, int, java.lang.String)(AssetManager.java:-2) waiters=3 in void rocks.tbog.tblauncher.icons.IconPackXML.load(android.content.pm.PackageManager) for 3.072s
W/tbog.tblaunche(20672):  Long monitor contention with owner UtilAsync #2 (20714) at long android.content.res.AssetManager.nativeOpenXmlAsset(long, int, java.lang.String)(AssetManager.java:-2) waiters=4 in void rocks.tbog.tblauncher.icons.IconPackXML.load(android.content.pm.PackageManager) for 2.949s
E/AndroidRuntime(20672):  FATAL EXCEPTION: main
E/AndroidRuntime(20672):  Process: rocks.tbog.tblauncher, PID: 20672
E/AndroidRuntime(20672):  java.lang.NullPointerException: Attempt to invoke virtual method 'boolean rocks.tbog.tblauncher.ui.AnimatedListView.post(java.lang.Runnable)' on a null object reference
E/AndroidRuntime(20672):  	at rocks.tbog.tblauncher.Behaviour.refreshSearchRecords(Behaviour.java:868)
E/AndroidRuntime(20672):  	at rocks.tbog.tblauncher.IconsHandler.lambda$loadIconsPack$1$IconsHandler(IconsHandler.java:142)
E/AndroidRuntime(20672):  	at rocks.tbog.tblauncher.-$$Lambda$IconsHandler$-6SNetl43xRw9R_2ufjIzkArOw0.run(Unknown Source:6)
E/AndroidRuntime(20672):  	at rocks.tbog.tblauncher.WorkAsync.RunnableTask.lambda$done$0$RunnableTask(RunnableTask.java:38)
E/AndroidRuntime(20672):  	at rocks.tbog.tblauncher.WorkAsync.-$$Lambda$RunnableTask$IDrDbtnj3Scfa8oyPMxyCwUIZ7Y.run(Unknown Source:2)
E/AndroidRuntime(20672):  	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(20672):  	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(20672):  	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(20672):  	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime(20672):  	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(20672):  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
E/AndroidRuntime(20672):  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```

## Context ##

This has happened several times when updating an app via F-Droid (may or may not have been a coincidence).

## Device info ##

  * OS: Android 10
  * TinyBit Launcher version: 6.4

**Comment by ltGuillaume** [comment]
I think this has been fixed in v6.4-add_pages 😃
